[COMMON]
port                            = 41555
# 是否开启双向HTTPS认证
open_tls                        = false


[MySQL]
url                             = "127.0.0.1:3306"
user                            = "root"
pwd                             = "niuge"
db_name                          = "niuniumart"
